name: ðŸš€ Deploy Release

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Submodules
        run: git submodule update --init

      # Deploy to local repo
      - name: Deploy to Release Branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: release
          FOLDER: addons/GodotFixedVolatilePhysics
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        run: |
          mkdir release
          mv addons/GodotFixedVolatilePhysics release
          pushd release
          zip -r ../Release.zip *
          popd

      - name: Upload Release
        uses: actions/upload-artifact@v2
        with:
          name: Release
          path: release

      - name: Tagged Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Release.zip
